[workspace]
members = ["geozero", "geozero-core", "geozero-cli"]
default-members = ["geozero", "geozero-core", "geozero-cli"]

[patch.crates-io]
# Patch flatgeobuf dependency (dev only)
geozero = { version = "0.2", path = "geozero" }
