[workspace]
members = ["geozero", "geozero-core", "geozero-shp", "geozero-cli", "geozero-bench"]
default-members = ["geozero", "geozero-core", "geozero-shp", "geozero-cli"]

[patch.crates-io]
# Patch geozero dependency (dev only)
geozero = { path = "geozero" }
