[package]
name = "geozero"
version = "0.5.3"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"
description = "Zero-Copy reading and writing of geospatial data."
homepage = "https://github.com/georust/geozero"
repository = "https://github.com/georust/geozero"
readme = "../README.md"
license = "MIT/Apache-2.0"
keywords = ["geo", "spatial"]

[dependencies]
thiserror = "1.0"
async-trait = "0.1"
seek_bufread = "1.2"
