[package]
name = "geozero-shp"
version = "0.1.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"
homepage = "https://github.com/georust/geozero"
repository = "https://github.com/georust/geozero"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["geo", "shapefile"]

[dependencies]
thiserror = "1.0"
geozero = "0.6.0"
byteorder = "1.2.7"
dbase = "0.0.4"

[dev-dependencies]
geozero-core = "0.5"
