[package]
name = "geozero-bench"
version = "0.1.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"
description = "GeoZero benchmark."
homepage = "https://github.com/georust/geozero"
repository = "https://github.com/georust/geozero"
license = "MIT/Apache-2.0"

[dependencies]
geozero = { version = "0.5", path = "../geozero" }
geozero-core = { version = "0.5", path = "../geozero-core", features = ["gdal-lib", "geos-lib", "gpkg", "postgis-sqlx", "postgis-postgres"] }
sqlx = { version = "0.4.0", default-features = false, features = [ "runtime-tokio-native-tls", "postgres", "sqlite" ] }
futures-util = "0.3.5"
geojson = { version = "0.18" }
criterion = "0.3"
geo-types = { version = "0.5", default-features = false }
geo = { version = "0.13" }  # , features = ["postgis-integration"] # not compatible with postgis = "0.7"
flatgeobuf = "0.3.4"
seek_bufread = "1.2"
postgres = "0.17"
postgis = "0.7"
gdal = { version = "0.6", default-features = false }
gdal-sys = { version = "0.2" }
tokio = { version = "0.2", default-features = false, features = ["rt-threaded"] }

[[bench]]
name = "geobench"
harness = false
