[package]
name = "geozero-cli"
version = "0.1.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"
default-run = "geozero"

[[bin]]
name = "geozero"
path = "src/main.rs"

[dependencies]
geozero-api = { path = "../geozero-api" }
geozero-core = { path = "../geozero-core" }
flatgeobuf = { git = "https://github.com/pka/flatgeobuf/", branch="geozero" }
structopt = "0.3"
tokio = { version = "0.2", features = ["full"] }
