[package]
name = "geozero-cli"
version = "0.1.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"
default-run = "geozero"

[[bin]]
name = "geozero"
path = "src/main.rs"

[dependencies]
geozero = "0.5"
geozero-core = "0.5"
flatgeobuf = "0.3.4"
structopt = "0.3"
tokio = { version = "0.2", features = ["full"] }
