[package]
name = "geozero-core"
version = "0.2.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
edition = "2018"
description = "Zero-Copy reading and writing of geospatial data."
homepage = "https://github.com/pka/geozero"
repository = "https://github.com/pka/geozero"
readme = "../README.md"
license = "MIT/Apache-2.0"
keywords = ["geo", "spatial", "geojson", "svg", "wkt"]

[dependencies]
geozero = { version = "0.2", path = "../geozero" }
geojson = { version =  "0.18" }

[dev-dependencies]
kdbush = "0.2"
